kind: pipeline
name: MvPro-Go Pipeline
platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request
#  paths:
#    include:
#      - README.md

environment:
  CGO_ENABLED: 0

steps:
- name: run linter
  image: golangci/golangci-lint:v1.54-alpine
  commands:
    - golangci-lint run

- name: scan the files
  image: aquasec/trivy:0.45.1
  commands:
    - trivy fs --exit-code 1 --scanners vuln,config ./
    - trivy config --exit-code 1 ./

- name: go build
  image: golang:1.21.2-alpine3.18
  commands:
    - go vet ./...
    - go test ./...
    - go build ./examples/...
